# Generated by Django 5.1.7 on 2025-03-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='name',
            field=models.CharField(default='Lal Bati Hyd', max_length=100),
            preserve_default=False,
        ),
    ]
