# Generated by Django 5.1.7 on 2025-03-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0002_hospitalmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_age', models.IntegerField()),
                ('patient_medical_expenditures', models.IntegerField()),
                ('patient_admitted_on', models.DateTimeField(editable=False)),
                ('patient_admitted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospitalmodel')),
            ],
        ),
    ]
