# Generated by Django 5.1.7 on 2025-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_admitted_on',
            field=models.DateTimeField(),
        ),
    ]
